### ISSUE TITLE
Question Regarding Build Process

### ISSUE THREAD

**Issue by NicholasMoser** [derWallace/org.eclipse.osgi#1]
Hello,

I'm needing to do something similar for version 3.7.2 of this same jar. Were you ever able to build the project? Or did you just open the jar with a zip utility and manually change the profile? I'm trying to figure out how this jar is actually built, but I don't see any kind of ant script, pom, gradle file, etc.

Thanks!

**Comment by derWallace** [comment]
Hi Nicholas,

well I manually added the profile and integrated that file into our target plattform as basis for our CI pipline to build our RCP product.

br,
Stefan

**Comment by NicholasMoser** [comment]
Gotcha, thanks for the information! 😄
